/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CipherBundle */

#ifndef _Included_CipherBundle
#define _Included_CipherBundle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CipherBundle
 * Method:    init
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_CipherBundle_init
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     CipherBundle
 * Method:    cryptString
 * Signature: (JLjava/lang/String;J[J)I
 */
JNIEXPORT jint JNICALL Java_CipherBundle_cryptString
  (JNIEnv *, jclass, jlong, jstring, jlong, jlongArray);

/*
 * Class:     CipherBundle
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CipherBundle_freeMemory
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
